services:
  - type: web
    name: medilogic-cataligne
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: IMGBB_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        value: essowasainfo60@gmail.com
      - key: ADMIN_PASSWORD
        value: essowasa1234A
    pythonVersion: 3.12